export class SimulationConstants {
  static DEFAULT_CANVAS_WIDTH = 768;
  static DEFAULT_CANVAS_HEIGHT = 768;
  static DEFAULT_CREATURES_COUNT = 100;
  static DEFAULT_FPS_MS = 1000 / 60;
  static DEFAULT_FOOD_PER_ROUND = 25;
  static DEFAULT_MAXIMUM_SPEED = 5;
  static DEFAULT_MINIMUM_SPEED = 25;
  static DEFAULT_MINIMUM_VISION_RANGE = 25;
  static DEFAULT_MAXIMUM_VISION_RANGE = 100;
}
